In [1]:
import numpy as np

In [22]:
a=np.array([2,3,4])      # an array
b=np.array([[1,2,3],[2,3,4]])
c=np.array([[[1,2],[2,3],[3,4]],[[2,3],[3,4],[4,5]]])

In [3]:
a                             #?

array([2, 3, 4])

In [10]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [23]:
c

array([[[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [12]:
a.ndim                    #dimension

2

In [11]:
b.ndim

2

In [24]:
c.ndim

3

In [5]:
a.size                    #size

3

In [13]:
b.size

6

In [25]:
c.size

12

In [6]:
a.shape                  #shape

(3,)

In [14]:
b.shape

(2, 3)

In [21]:
c.shape

(2, 3, 2)

In [8]:
a.dtype                  #datatype

dtype('int64')

In [15]:
b.dtype

dtype('int64')

In [26]:
c.dtype

dtype('int64')

In [34]:
np.arange(5)             #arange...............same like range

array([0, 1, 2, 3, 4])

In [30]:
np.arange(12).reshape(3,4)       #reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
np.arange(12,22,2)              #start,end,gap

array([12, 14, 16, 18, 20])

In [32]:
np.arange(12,16)                #start,end

array([12, 13, 14, 15])

In [33]:
np.zeros((2,3))                 #zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.array([1.3,2.0,3])            #auto typecasting

array([1.3, 2. , 3. ])

In [37]:
np.linspace(1,100,10)              #count btw start,end              #Linspace

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [42]:
dd=np.arange(6).reshape(1,1,1,1,1,6)             #?create a
dd

array([[[[[[0, 1, 2, 3, 4, 5]]]]]])

In [43]:
dd.ravel()

array([0, 1, 2, 3, 4, 5])

In [44]:
np.random.rand()                     #Random Numbers

0.7892500670926748

In [46]:
                                                  #any random integer between 10 to 100
int(np.random.rand()*100)

72

In [47]:
np.random.randint(35,100)

96

In [48]:
np.sqrt(np.random.randint(10,100,12).reshape(2,2,3))

array([[[7.34846923, 8.36660027, 6.08276253],
        [7.14142843, 6.08276253, 9.53939201]],

       [[4.89897949, 9.16515139, 6.55743852],
        [6.        , 4.47213595, 5.74456265]]])

In [56]:
np.round(5.6)              #Round

6.0

In [57]:
np.round(5.4)

5.0

In [58]:
np.ceil(5.6)                 #ceil

6.0

In [59]:
np.ceil(5.4)

6.0

In [60]:
np.floor(5.7)               #floor

5.0

In [61]:
np.floor(5.4)

5.0

In [63]:
np.log10(100)             #log

2.0

In [64]:
np.log(100)

4.605170185988092

In [67]:
q=np.arange(16).reshape(2,8)                       #Horozontal,vertical SPLIT
q

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [68]:
np.hsplit(q,2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]]), array([[ 4,  5,  6,  7],
        [12, 13, 14, 15]])]

In [69]:
np.vsplit(q,2)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]), array([[ 8,  9, 10, 11, 12, 13, 14, 15]])]

In [70]:
aa=np.arange(9).reshape(3,3)             #Horizontal,vertical stack
bb=np.arange(11,20).reshape(3,3)

In [73]:
np.hstack((aa,bb))

array([[ 0,  1,  2, 11, 12, 13],
       [ 3,  4,  5, 14, 15, 16],
       [ 6,  7,  8, 17, 18, 19]])

In [74]:
np.vstack((aa,bb))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [89]:
z=np.array([1+2,1+3],dtype='float')               #?

In [90]:
z

array([3., 4.])

In [93]:
z.dtype

dtype('float64')